version: '2.15.1'
services:
  dbpostgresql:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=family-password
      - POSTGRES_USER=family-user
      - POSTGRES_DB=family
  family-app:
    build:
      context: ./FamilyApp
      dockerfile: Dockerfile
    image: family-app
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
    restart: on-failure
  familymember-app:
    build:
      context: ./FamilyMemberApp
      dockerfile: Dockerfile
    image: familymember-app
    ports:
      - "8081:8081"
    depends_on:
      - dbpostgresql
    restart: on-failure